config/routes.rb
ReceiptCapture::Application.routes.draw do
  resources :receipts

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  attr_accessible :name, :price, :receipt_id
  belongs_to :receipt
end

app/models/receipt.rb
class Receipt < ActiveRecord::Base
  attr_accessible :company, :total
  has_many :line_items
  accepts_nested_attributes_for :line_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  # GET /receipts
  # GET /receipts.json
  def index
    @receipts = Receipt.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @receipts }
    end
  end

  # GET /receipts/1
  # GET /receipts/1.json
  def show
    @receipt = Receipt.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @receipt }
    end
  end

  # GET /receipts/new
  # GET /receipts/new.json
  def new
    @receipt = Receipt.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @receipt }
    end
  end

  # GET /receipts/1/edit
  def edit
    @receipt = Receipt.find(params[:id])
  end

  # POST /receipts
  # POST /receipts.json
  def create
    @receipt = Receipt.new(params[:receipt])
    @receipt.line_items.build

    respond_to do |format|
      if @receipt.save
        format.html { redirect_to @receipt, notice: 'Receipt was successfully created.' }
        format.json { render json: @receipt, status: :created, location: @receipt }
      else
        format.html { render action: "new" }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /receipts/1
  # PUT /receipts/1.json
  def update
    @receipt = Receipt.find(params[:id])

    respond_to do |format|
      if @receipt.update_attributes(params[:receipt])
        format.html { redirect_to @receipt, notice: 'Receipt was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receipts/1
  # DELETE /receipts/1.json
  def destroy
    @receipt = Receipt.find(params[:id])
    @receipt.destroy

    respond_to do |format|
      format.html { redirect_to receipts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReceiptCapture</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/receipts/_form.html.erb
<%= form_for(@receipt) do |f| %>
  <% if @receipt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@receipt.errors.count, "error") %> prohibited this receipt from being saved:</h2>

      <ul>
      <% @receipt.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :company %><br />
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :total %><br />
    <%= f.text_field :total %>
  </div>
	<div>
		<%= @receipt.line_items.each do |line_item| %>
			<%= f.fields_for line_item, :index => line_item do |line_item_form| %>
				<div class="field">
					<%= line_item_form.label :name %><br />
					<%= line_item_form.text_field :name %>
				</div>
			<% end %>
		<% end %>
	</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/receipts/edit.html.erb
<h1>Editing receipt</h1>

<%= render 'form' %>

<%= link_to 'Show', @receipt %> |
<%= link_to 'Back', receipts_path %>

app/views/receipts/index.html.erb
<h1>Listing receipts</h1>

<table>
  <tr>
    <th>Company</th>
    <th>Total</th>
    <th>Number of Line Items</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @receipts.each do |receipt| %>
  <tr>
    <td><%= receipt.company %></td>
    <td class="currency"><%= number_to_currency(receipt.total) %></td>
		<td><%= receipt.line_items.count() %></td>
    <td><%= link_to 'Show', receipt %></td>
    <td><%= link_to 'Edit', edit_receipt_path(receipt) %></td>
    <td><%= link_to 'Destroy', receipt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
	<tr>
		<td>Grand Total</td>
		<td ><%= number_to_currency(@receipts.sum(&:total)) %></td>
		<td colspan="4" />
	</tr>
</table>

<br />

<%= link_to 'New Receipt', new_receipt_path %>

app/views/receipts/new.html.erb
<h1>New receipt</h1>

<%= render 'form' %>

<%= link_to 'Back', receipts_path %>

app/views/receipts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Company:</b>
  <%= @receipt.company %>
</p>

<p>
  <b>Total:</b>
  <%= @receipt.total %>
</p>


<%= link_to 'Edit', edit_receipt_path(@receipt) %> |
<%= link_to 'Back', receipts_path %>